services:
  frontend:
    build:
      context: .
      # we need to use both args and environment to make variables accessible during build time.
      args:
        - BACKEND_URL=${BACKEND_URL}
        - NEXT_PUBLIC_SIGNALR_PORT=${NEXT_PUBLIC_SIGNALR_PORT}
    ports:
      - "80:3000"