services:
  backend:
    image: backend
    build:
      context: backend/
    ports:
      - 3001:3001
  frontend:
    # For pre-rendering nextjs pages
    depends_on:
      - backend
    image: frontend
    build:
      context: frontend/
    ports:
      - 80:3000
