services:
  backend:
    image: backend
    restart: unless-stopped
    build:
      context: backend/
    ports:
      - 3001:3001
  frontend:
    # For pre-rendering nextjs pages
    depends_on:
      - backend
    restart: unless-stopped
    image: frontend
    build:
      context: frontend/
  caddy:
    image: caddy
    restart: unless-stopped
    build:
      context: ./caddy/
    ports:
      - 80:80
      - "443:443"
      - "443:443/udp"
    develop:
      watch:
        - path: ./caddy/
        - action: rebuild
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
