services:
  backend:
    image: backend
    build:
      context: backend/
    ports:
      - 3001:3001
  frontend:
    # For pre-rendering nextjs pages
    depends_on:
      - backend
    image: frontend
    build:
      context: frontend/
      # we need to use both args and environment to make variables accessible during build time.
      args:
        - BACKEND_URL=${BACKEND_URL}
        - NEXT_PUBLIC_SIGNALR_PORT=${NEXT_PUBLIC_SIGNALR_PORT}
        - DEMO_USER_EMAIL=${DEMO_USER_EMAIL}
        - DEMO_USER_PASSWORD=${DEMO_USER_PASSWORD}
    ports:
      - 80:3000
