import type { Metadata } from "next";
import "./globals.css";
import SignalRProvider from "@providers/SignalRProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SignalRProvider>{children}</SignalRProvider>
      </body>
    </html>
  );
}
