import type { Metadata } from "next";
import "./globals.css";
import SignalRProvider from "@providers/SignalRProvider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Suspense>
          <SignalRProvider>{children}</SignalRProvider>
        </Suspense>
      </body>
    </html>
  );
}
