import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="bg-white dark:bg-gray-950 text-black dark:text-white"
    >
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
